name: refresh-data
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '16 6 * * 1' # runs every Monday at 6:16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Initialize python env
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests steam tqdm beautifulsoup4 lxml
      - name: Clone steam_stats
        run: |
          git clone https://github.com/dbeley/steam_stats
      - name: Extract Steam appids of owned games
        run: |
          python steam_stats/scripts/get_ids.py -u $STEAM_USERID -f ids.csv -t owned
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USERID: ${{ secrets.STEAM_USERID }}
      - name: Extract playtime data
        run: |
          python steam_stats/scripts/get_playtime.py -u $STEAM_USERID -f playtime.csv
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USERID: ${{ secrets.STEAM_USERID }}
      - name: Extract Steam data from appids
        run: |
          python -m steam_stats.steam_stats -f ids.csv --export_filename game_info.csv
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USERID: ${{ secrets.STEAM_USERID }}
      - name: Create new export
        run: |
          python create_export.py
      - name: Clean repository
        run: |
          git rm --cached steam_stats
          git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
