name: refresh-data
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '16 6 * * 1' # runs every Monday at 6:16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Initialize python env
        run: |
          python -m pip install --upgrade pip
      - name: Extract Steam appids of owned games
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USERID: ${{ secrets.STEAM_USERID }}
      - name: Extract Steam data from appids
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USERID: ${{ secrets.STEAM_USERID }}
      - name: Create new export
        run: |
          python create_export.py
      - name: Pull Remote Changes
        run: git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
